title: Pham Duc Manh
logo: 
description: Energetic student with balanced background in sports and extra-curricular activities. Diligent about preparing for examinations, competitions and assignments. Reliable and responsible with good communication and relationship-building abilities.
theme: jekyll-theme-minimal
